// <auto-generated />
using System;
using MVC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001111709_SeedRooms")]
    partial class SeedRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MVC.Models.BookingModel", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MVC.Models.RoomsModel", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomBuilding")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomFloor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RoomScreen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RoomWhiteboard")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 101,
                            RoomBuilding = "Pilestredet 35",
                            RoomCapacity = 10,
                            RoomFloor = 1,
                            RoomScreen = true,
                            RoomWhiteboard = false
                        },
                        new
                        {
                            RoomId = 102,
                            RoomBuilding = "Pilestredet 35",
                            RoomCapacity = 6,
                            RoomFloor = 3,
                            RoomScreen = true,
                            RoomWhiteboard = true
                        },
                        new
                        {
                            RoomId = 103,
                            RoomBuilding = "Pilestredet 35",
                            RoomCapacity = 4,
                            RoomFloor = 4,
                            RoomScreen = false,
                            RoomWhiteboard = true
                        },
                        new
                        {
                            RoomId = 104,
                            RoomBuilding = "Pilestredet 32",
                            RoomCapacity = 4,
                            RoomFloor = 6,
                            RoomScreen = false,
                            RoomWhiteboard = true
                        },
                        new
                        {
                            RoomId = 105,
                            RoomBuilding = "Pilestredet 48",
                            RoomCapacity = 8,
                            RoomFloor = 2,
                            RoomScreen = true,
                            RoomWhiteboard = true
                        },
                        new
                        {
                            RoomId = 106,
                            RoomBuilding = "Pilestredet 48",
                            RoomCapacity = 2,
                            RoomFloor = 5,
                            RoomScreen = false,
                            RoomWhiteboard = false
                        },
                        new
                        {
                            RoomId = 107,
                            RoomBuilding = "Holbergs terrasse",
                            RoomCapacity = 12,
                            RoomFloor = 1,
                            RoomScreen = true,
                            RoomWhiteboard = false
                        },
                        new
                        {
                            RoomId = 108,
                            RoomBuilding = "Holbergs terrasse",
                            RoomCapacity = 6,
                            RoomFloor = 3,
                            RoomScreen = true,
                            RoomWhiteboard = true
                        });
                });

            modelBuilder.Entity("MVC.Models.BookingModel", b =>
                {
                    b.HasOne("MVC.Models.RoomsModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
